<?php

namespace App\Traits;

trait TestimonialTrait
{

    public static $TESTIMONIAL_CREATED = 'TESTIMONIAL_CREATED';
    public static $TESTIMONIAL_CREATION_ERROR = 'TESTIMONIAL_CREATION_ERROR';

    public static $TESTIMONIAL_NOT_FOUND = 'TESTIMONIAL_NOT_FOUND';
    public static $TESTIMONIAL_FOUND = 'TESTIMONIAL_FOUND';

    public static $TESTIMONIAL_NOT_UPDATED = 'TESTIMONIAL_NOT_UPDATED';
    public static $TESTIMONIAL_UPDATED = 'TESTIMONIAL_UPDATED';

    public static $TESTIMONIAL_NOT_DELETED = 'TESTIMONIAL_NOT_DELETED';
    public static $TESTIMONIAL_DELETED = 'TESTIMONIAL_DELETED';

    public static $TESTIMONIAL_NOT_RESTORED = 'TESTIMONIAL_NOT_RESTORED';
    public static $TESTIMONIAL_RESTORED = 'TESTIMONIAL_RESTORED';
}
