<?php

namespace App\Traits;

trait WhitelistedDataTrait
{

    public static $WHITELISTED_DATA_CREATED = 'WHITELISTED_DATA_CREATED';
    public static $WHITELISTED_DATA_CREATION_ERROR = 'WHITELISTED_DATA_CREATION_ERROR';

    public static $WHITELISTED_DATA_NOT_FOUND = 'WHITELISTED_DATA_NOT_FOUND';
    public static $WHITELISTED_DATA_FOUND = 'WHITELISTED_DATA_FOUND';

    public static $WHITELISTED_DATA_NOT_UPDATED = 'WHITELISTED_DATA_NOT_UPDATED';
    public static $WHITELISTED_DATA_UPDATED = 'WHITELISTED_DATA_UPDATED';

    public static $WHITELISTED_DATA_NOT_DELETED = 'WHITELISTED_DATA_NOT_DELETED';
    public static $WHITELISTED_DATA_DELETED = 'WHITELISTED_DATA_DELETED';

    public static $WHITELISTED_DATA_NOT_RESTORED = 'WHITELISTED_DATA_NOT_RESTORED';
    public static $WHITELISTED_DATA_RESTORED = 'WHITELISTED_DATA_RESTORED';
}
